name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
         images: ${{ secrets.DOCKER_USER_NAME }}/hello-world
         tags: |
           type=ref,event=branch
           type=raw,value=latest

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
